# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 06 Nov 2014 00:10:16 +0000
*	@ALL	1
*	@member	8
bac_a_sable:*	@ALL	16
