<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: 1234:JoeBlack
 * Date: Thu, 06 Nov 2014 02:35:41 +0100
 */

$conf['title'] = 'Mensa France - Wiki Interne';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-zero';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = '@manager';
$conf['disableactions'] = 'register';
$conf['mailguard'] = 'none';
$conf['userewrite'] = '1';

// end auto-generated content
