<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 06 Nov 2014 00:10:16 +0000
 */
$conf['title'] = 'Mensa France - Wiki Interne';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-zero';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
